# Generated by Django 3.1.1 on 2020-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0002_donation_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'non-government organisation'), (2, 'local collection'), (3, 'foundation')], default=3),
        ),
    ]
