# Generated by Django 3.1.1 on 2020-09-15 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0003_donation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
