# Generated by Django 3.1.1 on 2020-09-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0005_auto_20200915_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='confrimation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
