# Generated by Django 3.1.1 on 2020-09-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0006_donation_confrimation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='confrimation_date',
            field=models.DateField(blank=True, default='Null', null=True),
        ),
    ]
