# Generated by Django 3.1.1 on 2020-09-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0008_auto_20200915_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
